// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fa.context;

#nullable disable

namespace FADataAccessLibrary.Migrations
{
    [DbContext(typeof(AccountMasterContext))]
    [Migration("20241125061904_AddRoomRent")]
    partial class AddRoomRent
    {
    }
}
