using fa.model.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FADataAccessLibrary.Configuration
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                new Country() { Id = 1, Name = "Afghanistan", ISOCode2 = "AF", ISOCode3 = "AFG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 2, Name = "Albania", ISOCode2 = "AL", ISOCode3 = "ALB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 3, Name = "Algeria", ISOCode2 = "DZ", ISOCode3 = "DZA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 4, Name = "American Samoa", ISOCode2 = "AS", ISOCode3 = "ASM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 5, Name = "Andorra", ISOCode2 = "AD", ISOCode3 = "AND", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 6, Name = "Angola", ISOCode2 = "AO", ISOCode3 = "AGO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 7, Name = "Anguilla", ISOCode2 = "AI", ISOCode3 = "AIA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 8, Name = "Antarctica", ISOCode2 = "AQ", ISOCode3 = "ATA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 9, Name = "Antigua and Barbuda", ISOCode2 = "AG", ISOCode3 = "ATG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 10, Name = "Argentina", ISOCode2 = "AR", ISOCode3 = "ARG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 11, Name = "Armenia", ISOCode2 = "AM", ISOCode3 = "ARM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 12, Name = "Aruba", ISOCode2 = "AW", ISOCode3 = "ABW", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 13, Name = "Australia", ISOCode2 = "AU", ISOCode3 = "AUS", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 14, Name = "Austria", ISOCode2 = "AT", ISOCode3 = "AUT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 15, Name = "Azerbaijan", ISOCode2 = "AZ", ISOCode3 = "AZE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 16, Name = "Bahamas", ISOCode2 = "BS", ISOCode3 = "BHS", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 17, Name = "Bahrain", ISOCode2 = "BH", ISOCode3 = "BHR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 18, Name = "Bangladesh", ISOCode2 = "BD", ISOCode3 = "BGD", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 19, Name = "Barbados", ISOCode2 = "BB", ISOCode3 = "BRB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 20, Name = "Belarus", ISOCode2 = "BY", ISOCode3 = "BLR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 21, Name = "Belgium", ISOCode2 = "BE", ISOCode3 = "BEL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 22, Name = "Belize", ISOCode2 = "BZ", ISOCode3 = "BLZ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 23, Name = "Benin", ISOCode2 = "BJ", ISOCode3 = "BEN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 24, Name = "Bermuda", ISOCode2 = "BM", ISOCode3 = "BMU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 25, Name = "Bhutan", ISOCode2 = "BT", ISOCode3 = "BTN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 26, Name = "Bolivia", ISOCode2 = "BO", ISOCode3 = "BOL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 27, Name = "Bosnia and Herzegowina", ISOCode2 = "BA", ISOCode3 = "BIH", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 28, Name = "Botswana", ISOCode2 = "BW", ISOCode3 = "BWA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 29, Name = "Bouvet Island", ISOCode2 = "BV", ISOCode3 = "BVT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 30, Name = "Brazil", ISOCode2 = "BR", ISOCode3 = "BRA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 31, Name = "British Indian Ocean Territory", ISOCode2 = "IO", ISOCode3 = "IOT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 32, Name = "Brunei Darussalam", ISOCode2 = "BN", ISOCode3 = "BRN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 33, Name = "Bulgaria", ISOCode2 = "BG", ISOCode3 = "BGR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 34, Name = "Burkina Faso", ISOCode2 = "BF", ISOCode3 = "BFA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 35, Name = "Burundi", ISOCode2 = "BI", ISOCode3 = "BDI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 36, Name = "Cambodia", ISOCode2 = "KH", ISOCode3 = "KHM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 37, Name = "Cameroon", ISOCode2 = "CM", ISOCode3 = "CMR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 38, Name = "Canada", ISOCode2 = "CA", ISOCode3 = "CAN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 39, Name = "Cape Verde", ISOCode2 = "CV", ISOCode3 = "CPV", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 40, Name = "Cayman Islands", ISOCode2 = "KY", ISOCode3 = "CYM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 41, Name = "Central African Republic", ISOCode2 = "CF", ISOCode3 = "CAF", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 42, Name = "Chad", ISOCode2 = "TD", ISOCode3 = "TCD", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 43, Name = "Chile", ISOCode2 = "CL", ISOCode3 = "CHL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 44, Name = "China", ISOCode2 = "CN", ISOCode3 = "CHN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 45, Name = "Christmas Island", ISOCode2 = "CX", ISOCode3 = "CXR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 46, Name = "Cocos (Keeling) Islands", ISOCode2 = "CC", ISOCode3 = "CCK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 47, Name = "Colombia", ISOCode2 = "CO", ISOCode3 = "COL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 48, Name = "Comoros", ISOCode2 = "KM", ISOCode3 = "COM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 49, Name = "Congo", ISOCode2 = "CG", ISOCode3 = "COG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 50, Name = "Cook Islands", ISOCode2 = "CK", ISOCode3 = "COK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 51, Name = "Costa Rica", ISOCode2 = "CR", ISOCode3 = "CRI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 52, Name = "Cote D Ivoire", ISOCode2 = "CI", ISOCode3 = "CIV", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 53, Name = "Croatia", ISOCode2 = "HR", ISOCode3 = "HRV", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 54, Name = "Cuba", ISOCode2 = "CU", ISOCode3 = "CUB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 55, Name = "Cyprus", ISOCode2 = "CY", ISOCode3 = "CYP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 56, Name = "Czech Republic", ISOCode2 = "CZ", ISOCode3 = "CZE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 57, Name = "Denmark", ISOCode2 = "DK", ISOCode3 = "DNK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 58, Name = "Djibouti", ISOCode2 = "DJ", ISOCode3 = "DJI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 59, Name = "Dominica", ISOCode2 = "DM", ISOCode3 = "DMA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 60, Name = "Dominican Republic", ISOCode2 = "DO", ISOCode3 = "DOM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 61, Name = "East Timor", ISOCode2 = "TP", ISOCode3 = "TMP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 62, Name = "Ecuador", ISOCode2 = "EC", ISOCode3 = "ECU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 63, Name = "Egypt", ISOCode2 = "EG", ISOCode3 = "EGY", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 64, Name = "El Salvador", ISOCode2 = "SV", ISOCode3 = "SLV", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 65, Name = "Equatorial Guinea", ISOCode2 = "GQ", ISOCode3 = "GNQ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 66, Name = "Eritrea", ISOCode2 = "ER", ISOCode3 = "ERI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 67, Name = "Estonia", ISOCode2 = "EE", ISOCode3 = "EST", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 68, Name = "Ethiopia", ISOCode2 = "ET", ISOCode3 = "ETH", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 69, Name = "Falkland Islands (Malvinas)", ISOCode2 = "FK", ISOCode3 = "FLK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 70, Name = "Faroe Islands", ISOCode2 = "FO", ISOCode3 = "FRO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 71, Name = "Fiji", ISOCode2 = "FJ", ISOCode3 = "FJI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 72, Name = "Finland", ISOCode2 = "FI", ISOCode3 = "FIN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 73, Name = "France", ISOCode2 = "FR", ISOCode3 = "FRA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 74, Name = "France", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 75, Name = "French Guiana", ISOCode2 = "GF", ISOCode3 = "GUF", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 76, Name = "French Polynesia", ISOCode2 = "PF", ISOCode3 = "PYF", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 77, Name = "French Southern Territories", ISOCode2 = "TF", ISOCode3 = "ATF", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 78, Name = "Gabon", ISOCode2 = "GA", ISOCode3 = "GAB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 79, Name = "Gambia", ISOCode2 = "GM", ISOCode3 = "GMB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 80, Name = "Georgia", ISOCode2 = "GE", ISOCode3 = "GEO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 81, Name = "Germany", ISOCode2 = "DE", ISOCode3 = "DEU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 82, Name = "Ghana", ISOCode2 = "GH", ISOCode3 = "GHA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 83, Name = "Gibraltar", ISOCode2 = "GI", ISOCode3 = "GIB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 84, Name = "Greece", ISOCode2 = "GR", ISOCode3 = "GRC", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 85, Name = "Greenland", ISOCode2 = "GL", ISOCode3 = "GRL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 86, Name = "Grenada", ISOCode2 = "GD", ISOCode3 = "GRD", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 87, Name = "Guadeloupe", ISOCode2 = "GP", ISOCode3 = "GLP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 88, Name = "Guam", ISOCode2 = "GU", ISOCode3 = "GUM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 89, Name = "Guatemala", ISOCode2 = "GT", ISOCode3 = "GTM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 90, Name = "Guinea", ISOCode2 = "GN", ISOCode3 = "GIN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 91, Name = "Guinea-bissau", ISOCode2 = "GW", ISOCode3 = "GNB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 92, Name = "Guyana", ISOCode2 = "GY", ISOCode3 = "GUY", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 93, Name = "Haiti", ISOCode2 = "HT", ISOCode3 = "HTI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 94, Name = "Heard and Mc Donald Islands", ISOCode2 = "HM", ISOCode3 = "HMD", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 95, Name = "Honduras", ISOCode2 = "HN", ISOCode3 = "HND", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 96, Name = "Hong Kong", ISOCode2 = "HK", ISOCode3 = "HKG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 97, Name = "Hungary", ISOCode2 = "HU", ISOCode3 = "HUN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 98, Name = "Iceland", ISOCode2 = "IS", ISOCode3 = "ISL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 99, Name = "India", ISOCode2 = "IN", ISOCode3 = "IND", Active = true, DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 100, Name = "Indonesia", ISOCode2 = "ID", ISOCode3 = "IDN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 101, Name = "Iran (Islamic Republic of)", ISOCode2 = "IR", ISOCode3 = "IRN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 102, Name = "Iraq", ISOCode2 = "IQ", ISOCode3 = "IRQ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 103, Name = "Ireland", ISOCode2 = "IE", ISOCode3 = "IRL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 104, Name = "Israel", ISOCode2 = "IL", ISOCode3 = "ISR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 105, Name = "Italy", ISOCode2 = "IT", ISOCode3 = "ITA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 106, Name = "Jamaica", ISOCode2 = "JM", ISOCode3 = "JAM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 107, Name = "Japan", ISOCode2 = "JP", ISOCode3 = "JPN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 108, Name = "Jordan", ISOCode2 = "JO", ISOCode3 = "JOR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 109, Name = "Kazakhstan", ISOCode2 = "KZ", ISOCode3 = "KAZ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 110, Name = "Kenya", ISOCode2 = "KE", ISOCode3 = "KEN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 111, Name = "Kiribati", ISOCode2 = "KI", ISOCode3 = "KIR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 112, Name = "Korea", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 113, Name = "Korea", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 114, Name = "Kuwait", ISOCode2 = "KW", ISOCode3 = "KWT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 115, Name = "Kyrgyzstan", ISOCode2 = "KG", ISOCode3 = "KGZ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 116, Name = "Lao Peoples Democratic Republic", ISOCode2 = "LA", ISOCode3 = "LAO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 117, Name = "Latvia", ISOCode2 = "LV", ISOCode3 = "LVA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 118, Name = "Lebanon", ISOCode2 = "LB", ISOCode3 = "LBN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 119, Name = "Lesotho", ISOCode2 = "LS", ISOCode3 = "LSO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 120, Name = "Liberia", ISOCode2 = "LR", ISOCode3 = "LBR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 121, Name = "Libyan Arab Jamahiriya", ISOCode2 = "LY", ISOCode3 = "LBY", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 122, Name = "Liechtenstein", ISOCode2 = "LI", ISOCode3 = "LIE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 123, Name = "Lithuania", ISOCode2 = "LT", ISOCode3 = "LTU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 124, Name = "Luxembourg", ISOCode2 = "LU", ISOCode3 = "LUX", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 125, Name = "Macau", ISOCode2 = "MO", ISOCode3 = "MAC", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 126, Name = "Macedonia", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 127, Name = "Madagascar", ISOCode2 = "MG", ISOCode3 = "MDG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 128, Name = "Malawi", ISOCode2 = "MW", ISOCode3 = "MWI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 129, Name = "Malaysia", ISOCode2 = "MY", ISOCode3 = "MYS", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 130, Name = "Maldives", ISOCode2 = "MV", ISOCode3 = "MDV", Active = true, DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 131, Name = "Mali", ISOCode2 = "ML", ISOCode3 = "MLI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 132, Name = "Malta", ISOCode2 = "MT", ISOCode3 = "MLT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 133, Name = "Marshall Islands", ISOCode2 = "MH", ISOCode3 = "MHL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 134, Name = "Martinique", ISOCode2 = "MQ", ISOCode3 = "MTQ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 135, Name = "Mauritania", ISOCode2 = "MR", ISOCode3 = "MRT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 136, Name = "Mauritius", ISOCode2 = "MU", ISOCode3 = "MUS", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 137, Name = "Mayotte", ISOCode2 = "YT", ISOCode3 = "MYT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 138, Name = "Mexico", ISOCode2 = "MX", ISOCode3 = "MEX", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 139, Name = "Micronesia", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 140, Name = "Moldova", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 141, Name = "Monaco", ISOCode2 = "MC", ISOCode3 = "MCO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 142, Name = "Mongolia", ISOCode2 = "MN", ISOCode3 = "MNG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 143, Name = "Montserrat", ISOCode2 = "MS", ISOCode3 = "MSR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 144, Name = "Morocco", ISOCode2 = "MA", ISOCode3 = "MAR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 145, Name = "Mozambique", ISOCode2 = "MZ", ISOCode3 = "MOZ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 146, Name = "Myanmar", ISOCode2 = "MM", ISOCode3 = "MMR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 147, Name = "Namibia", ISOCode2 = "NA", ISOCode3 = "NAM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 148, Name = "Nauru", ISOCode2 = "NR", ISOCode3 = "NRU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 149, Name = "Nepal", ISOCode2 = "NP", ISOCode3 = "NPL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 150, Name = "Netherlands", ISOCode2 = "NL", ISOCode3 = "NLD", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 151, Name = "Netherlands Antilles", ISOCode2 = "AN", ISOCode3 = "ANT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 152, Name = "New Caledonia", ISOCode2 = "NC", ISOCode3 = "NCL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 153, Name = "New Zealand", ISOCode2 = "NZ", ISOCode3 = "NZL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 154, Name = "Nicaragua", ISOCode2 = "NI", ISOCode3 = "NIC", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 155, Name = "Niger", ISOCode2 = "NE", ISOCode3 = "NER", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 156, Name = "Nigeria", ISOCode2 = "NG", ISOCode3 = "NGA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 157, Name = "Niue", ISOCode2 = "NU", ISOCode3 = "NIU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 158, Name = "Norfolk Island", ISOCode2 = "NF", ISOCode3 = "NFK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 159, Name = "Northern Mariana Islands", ISOCode2 = "MP", ISOCode3 = "MNP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 160, Name = "Norway", ISOCode2 = "NO", ISOCode3 = "NOR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 161, Name = "Oman", ISOCode2 = "OM", ISOCode3 = "OMN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 162, Name = "Pakistan", ISOCode2 = "PK", ISOCode3 = "PAK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 163, Name = "Palau", ISOCode2 = "PW", ISOCode3 = "PLW", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 164, Name = "Panama", ISOCode2 = "PA", ISOCode3 = "PAN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 165, Name = "Papua New Guinea", ISOCode2 = "PG", ISOCode3 = "PNG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 166, Name = "Paraguay", ISOCode2 = "PY", ISOCode3 = "PRY", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 167, Name = "Peru", ISOCode2 = "PE", ISOCode3 = "PER", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 168, Name = "Philippines", ISOCode2 = "PH", ISOCode3 = "PHL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 169, Name = "Pitcairn", ISOCode2 = "PN", ISOCode3 = "PCN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 170, Name = "Poland", ISOCode2 = "PL", ISOCode3 = "POL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 171, Name = "Portugal", ISOCode2 = "PT", ISOCode3 = "PRT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 172, Name = "Puerto Rico", ISOCode2 = "PR", ISOCode3 = "PRI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 173, Name = "Qatar", ISOCode2 = "QA", ISOCode3 = "QAT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 174, Name = "Reunion", ISOCode2 = "RE", ISOCode3 = "REU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 175, Name = "Romania", ISOCode2 = "RO", ISOCode3 = "ROM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 176, Name = "Russian Federation", ISOCode2 = "RU", ISOCode3 = "RUS", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 177, Name = "Rwanda", ISOCode2 = "RW", ISOCode3 = "RWA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 178, Name = "Saint Kitts and Nevis", ISOCode2 = "KN", ISOCode3 = "KNA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 179, Name = "Saint Lucia", ISOCode2 = "LC", ISOCode3 = "LCA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 180, Name = "Saint Vincent and the Grenadines", ISOCode2 = "VC", ISOCode3 = "VCT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 181, Name = "Samoa", ISOCode2 = "WS", ISOCode3 = "WSM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 182, Name = "San Marino", ISOCode2 = "SM", ISOCode3 = "SMR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 183, Name = "Sao Tome and Principe", ISOCode2 = "ST", ISOCode3 = "STP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 184, Name = "Saudi Arabia", ISOCode2 = "SA", ISOCode3 = "SAU", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 185, Name = "Senegal", ISOCode2 = "SN", ISOCode3 = "SEN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 186, Name = "Seychelles", ISOCode2 = "SC", ISOCode3 = "SYC", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 187, Name = "Sierra Leone", ISOCode2 = "SL", ISOCode3 = "SLE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 188, Name = "Singapore", ISOCode2 = "SG", ISOCode3 = "SGP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 189, Name = "Slovakia (Slovak Republic)", ISOCode2 = "SK", ISOCode3 = "SVK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 190, Name = "Slovenia", ISOCode2 = "SI", ISOCode3 = "SVN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 191, Name = "Solomon Islands", ISOCode2 = "SB", ISOCode3 = "SLB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 192, Name = "Somalia", ISOCode2 = "SO", ISOCode3 = "SOM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 193, Name = "south Africa", ISOCode2 = "ZA", ISOCode3 = "ZAF", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 194, Name = "South Georgia and the South Sandwich Islands", ISOCode2 = "GS", ISOCode3 = "SGS", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 195, Name = "Spain", ISOCode2 = "ES", ISOCode3 = "ESP", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 196, Name = "Sri Lanka", ISOCode2 = "LK", ISOCode3 = "LKA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 197, Name = "St. Helena", ISOCode2 = "SH", ISOCode3 = "SHN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 198, Name = "St. Pierre and Miquelon", ISOCode2 = "PM", ISOCode3 = "SPM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 199, Name = "Sudan", ISOCode2 = "SD", ISOCode3 = "SDN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 200, Name = "Suriname", ISOCode2 = "SR", ISOCode3 = "SUR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 201, Name = "Svalbard and Jan Mayen Islands", ISOCode2 = "SJ", ISOCode3 = "SJM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 202, Name = "Swaziland", ISOCode2 = "SZ", ISOCode3 = "SWZ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 203, Name = "Sweden", ISOCode2 = "SE", ISOCode3 = "SWE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 204, Name = "Switzerland", ISOCode2 = "CH", ISOCode3 = "CHE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 205, Name = "Syrian Arab Republic", ISOCode2 = "SY", ISOCode3 = "SYR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 206, Name = "Taiwan", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 207, Name = "Tajikistan", ISOCode2 = "TJ", ISOCode3 = "TJK", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 208, Name = "Tanzania", ISOCode2 = " ", ISOCode3 = " ", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 209, Name = "Thailand", ISOCode2 = "TH", ISOCode3 = "THA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 210, Name = "Togo", ISOCode2 = "TG", ISOCode3 = "TGO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 211, Name = "Tokelau", ISOCode2 = "TK", ISOCode3 = "TKL", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 212, Name = "Tonga", ISOCode2 = "TO", ISOCode3 = "TON", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 213, Name = "Trinidad and Tobago", ISOCode2 = "TT", ISOCode3 = "TTO", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 214, Name = "Tunisia", ISOCode2 = "TN", ISOCode3 = "TUN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 215, Name = "Turkey", ISOCode2 = "TR", ISOCode3 = "TUR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 216, Name = "Turkmenistan", ISOCode2 = "TM", ISOCode3 = "TKM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 217, Name = "Turks and Caicos Islands", ISOCode2 = "TC", ISOCode3 = "TCA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 218, Name = "Tuvalu", ISOCode2 = "TV", ISOCode3 = "TUV", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 219, Name = "Uganda", ISOCode2 = "UG", ISOCode3 = "UGA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 220, Name = "Ukraine", ISOCode2 = "UA", ISOCode3 = "UKR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 221, Name = "United Arab Emirates", ISOCode2 = "AE", ISOCode3 = "ARE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 222, Name = "United Kingdom", ISOCode2 = "GB", ISOCode3 = "GBR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 223, Name = "United States", ISOCode2 = "US", ISOCode3 = "USA", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 224, Name = "United States Minor Outlying Islands", ISOCode2 = "UM", ISOCode3 = "UMI", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 225, Name = "Uruguay", ISOCode2 = "UY", ISOCode3 = "URY", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 226, Name = "Uzbekistan", ISOCode2 = "UZ", ISOCode3 = "UZB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 227, Name = "Vanuatu", ISOCode2 = "VU", ISOCode3 = "VUT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 228, Name = "Vatican City State (Holy See)", ISOCode2 = "VA", ISOCode3 = "VAT", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 229, Name = "Venezuela", ISOCode2 = "VE", ISOCode3 = "VEN", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 230, Name = "Viet Nam", ISOCode2 = "VN", ISOCode3 = "VNM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 231, Name = "Virgin Islands (British)", ISOCode2 = "VG", ISOCode3 = "VGB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 232, Name = "Virgin Islands (U.S.)", ISOCode2 = "VI", ISOCode3 = "VIR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 233, Name = "Wallis and Futuna Islands", ISOCode2 = "WF", ISOCode3 = "WLF", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 234, Name = "Western Sahara", ISOCode2 = "EH", ISOCode3 = "ESH", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 235, Name = "Yemen", ISOCode2 = "YE", ISOCode3 = "YEM", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 236, Name = "Yugoslavia", ISOCode2 = "YU", ISOCode3 = "YUG", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 237, Name = "Zaire", ISOCode2 = "ZR", ISOCode3 = "ZAR", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 238, Name = "Zambia", ISOCode2 = "ZM", ISOCode3 = "ZMB", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" },
                new Country() { Id = 239, Name = "Zimbabwe", ISOCode2 = "ZW", ISOCode3 = "ZWE", DefaultCurrencyId = 165, DefaultDateFormat = "MM/dd/yyyy" }
            );
        }
    }
}
